### PR TITLE
Fixed a bug in ATypeElementWithType.equals

### LINKED ISSUE #168: ATypeElementTypeWithType returns wrong values
Here's a minimal example:
Note: you'll need to make the constructor `ATypeElementWithType(Object o)` public in order for this to work, just for the test case.

    import scenelib.annotations.el.*;
    import scenelib.type.*;
    
    public class TestEquals {
        public static void main (String[] args) throws Exception {
            ATypeElementWithType e = new ATypeElementWithType("hello");
            ATypeElementWithType a = e.clone();
            a.setType( new ArrayType(new DeclaredType("hello")));
            e.setType( new DeclaredType("hello"));
            System.out.println(a.equals(e));
        }
    }

This will print `true`. This pull request fixes the issue: https://github.com/typetools/annotation-tools/pull/167

### PR DESCRIPTION
**Pull request by gsaga**
Here's a minimal example:
Note: you'll need to make the constructor ATypeElementWithType(Object o) public in order for this to work, just for the test case.

    import scenelib.annotations.el.*;
    import scenelib.type.*;
    public class TestEquals {
        public static void main (String[] args) throws Exception {
            ATypeElementWithType e = new ATypeElementWithType("hello");
            ATypeElementWithType a = e.clone();
            a.setType( new ArrayType(new DeclaredType("hello")));
            e.setType( new DeclaredType("hello"));
            System.out.println(a.equals(e));
        }
    }

This will print true.
Also fixes the method name so that it conforms to the format used by other classes in `AElement` hierarchy.
fixes #168

### CODE REVIEW

File: scene-lib/src/scenelib/annotations/el/ATypeElementWithType.java [hunk 1]
```diff
@@ -77,10 +77,10 @@ public void setType(Type type) {
     @Override
     public boolean equals(Object o) {
         return o instanceof ATypeElementWithType
-            && ((ATypeElementWithType) o).equals(this);
+            && ((ATypeElementWithType) o).equalsTypeElementWithType(this);
     }
 
-    public boolean equals(ATypeElementWithType o) {
+    public boolean equalsTypeElementWithType(ATypeElementWithType o) {
```
Comment (wmdietl) [inline scene-lib/src/scenelib/annotations/el/ATypeElementWithType.java]: With my comment at https://github.com/typetools/annotation-tools/pull/167#discussion_r186309144
I wanted to suggest to inline the separate `equalsTypeElementWithType` method into `equals(Object)`.
What is the point of adding this separate public method if nobody needs it?

Comment (gsaga) [reply scene-lib/src/scenelib/annotations/el/ATypeElementWithType.java]: Hi,
I thought about changing back the name because all the classes in the `AElement` hierarchy use double dispatching mechanism and it looked like a convention, and the double dispatching mechanism is more clear according to Michael.
This class is the only one for which the second equals method isn't used anywhere, and I'm not yet familiar with the complete codebase so I thought it was error prone to change the public api of the class, that's why I changed back the name and made the change so that the `equals(Object)` calls the correct method.
I do have the merged `equals` method in a branch. Should I make a pull request from it?

Comment (wmdietl) [reply scene-lib/src/scenelib/annotations/el/ATypeElementWithType.java]: Sure that sounds fine.
Some classes have non-public versions (e.g. `AMethod`and `ATypeElement`) whereas others have public `equalsXXX` methods with javadoc explaining the reason for having a separate method.
As your method is public, how about copying & adapting one of those javadoc comments?

**Comment by mernst** [comment]
Can you make a pull request that runs this test?

**Comment by mernst** [comment]
I simplified the code.
@wmdietl Could you take a quick look?
